version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - AUTOCOMPACT
  - bmad
  - cmdk
  - customizer
  - decisioning
  - drilldown
  - esac
  - glassmorphism
  - gpgsign
  - graphify
  - hideable
  - Laravel
  - Liskov
  - lucide
  - magick
  - majedsiefalnasr
  - nuqs
  - nuxtjs
  - offcanvas
  - phpunit
  - pkill
  - prefs
  - reka
  - reqs
  - rollups
  - shadcn
  - Socrati
  - socraticode
  - subcomponents
  - Tajawal
  - tanstack
  - Tasklist
  - tasklists
  - topbar
  - Touchpoints
  - tweakcn
  - unbuilt
  - Unovis
  - workes
  - worktrees
  - الإرياني
  - الحوكمة
  - الذبحاني
  - الذيباني
  - السويفت
  - السياني
  - الشرعبي
  - الشميري
  - الفلاتر
  - عبدالملك
ignoreWords: []
import: []
