/** 19 canonical workflow states — must match backend RequestStatus exactly */
export enum RequestStatus {
  DRAFT = 'DRAFT',
  DRAFT_REJECTED_INTERNAL = 'DRAFT_REJECTED_INTERNAL',
  SUBMITTED = 'SUBMITTED',
  BANK_REVIEW = 'BANK_REVIEW',
  BANK_APPROVED = 'BANK_APPROVED',
  BANK_RETURNED = 'BANK_RETURNED',
  SUPPORT_REVIEW_PENDING = 'SUPPORT_REVIEW_PENDING',
  SUPPORT_REVIEW_IN_PROGRESS = 'SUPPORT_REVIEW_IN_PROGRESS',
  SUPPORT_APPROVED = 'SUPPORT_APPROVED',
  SUPPORT_REJECTED = 'SUPPORT_REJECTED',
  WAITING_FOR_SWIFT = 'WAITING_FOR_SWIFT',
  SWIFT_UPLOADED = 'SWIFT_UPLOADED',
  WAITING_FOR_VOTING_OPEN = 'WAITING_FOR_VOTING_OPEN',
  EXECUTIVE_VOTING_OPEN = 'EXECUTIVE_VOTING_OPEN',
  EXECUTIVE_VOTING_CLOSED = 'EXECUTIVE_VOTING_CLOSED',
  EXECUTIVE_APPROVED = 'EXECUTIVE_APPROVED',
  EXECUTIVE_REJECTED = 'EXECUTIVE_REJECTED',
  CUSTOMS_DECLARATION_ISSUED = 'CUSTOMS_DECLARATION_ISSUED',
  COMPLETED = 'COMPLETED',
}

/** 8 canonical roles — must match backend UserRole exactly */
export enum UserRole {
  DATA_ENTRY = 'DATA_ENTRY',
  BANK_REVIEWER = 'BANK_REVIEWER',
  BANK_ADMIN = 'BANK_ADMIN',
  SWIFT_OFFICER = 'SWIFT_OFFICER',
  SUPPORT_COMMITTEE = 'SUPPORT_COMMITTEE',
  EXECUTIVE_MEMBER = 'EXECUTIVE_MEMBER',
  COMMITTEE_DIRECTOR = 'COMMITTEE_DIRECTOR',
  CBY_ADMIN = 'CBY_ADMIN',
}

export enum VoteType {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  ABSTAIN = 'ABSTAIN',
  AUTO_ABSTAIN_TIMEOUT = 'AUTO_ABSTAIN_TIMEOUT',
}

export enum Currency {
  USD = 'USD',
  EUR = 'EUR',
  SAR = 'SAR',
  AED = 'AED',
  CNY = 'CNY',
}

export enum VotingSessionStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  FINALIZED = 'FINALIZED',
}
