<?php

/**
 * Anchor catalog: 56 fixed request specifications (28 YBRD + 28 CAC).
 *
 * A001–A017: Base Lovable SAMPLE_REQUESTS × 2 banks, mapped to INV-YBRD-* / INV-CAC-* invoices
 * A018–A028: Edge scenarios per spec (returned_to_entry, claim_active, scan_pending, etc.)
 *
 * Each spec includes:
 *  - reference: ENG-2026-{BANK}-{A###}
 *  - bank: 'YBRD' | 'CAC'
 *  - scenario_key: identifies the active state / history path
 *  - current_stage: active stage code (CREATE, INTERNAL, SUPPORT, EXEC, FX, FX_CONFIRM, FINAL, CLOSED_*)
 *  - runtime_status: ACTIVE | CLOSED | REJECTED
 *  - path: ordered hops [from_stage, to_stage, action_code] (timestamps auto-monotonic)
 *  - sample: data fields (amount, invoice_number, request_percentage, etc.)
 */
return [
    // ── YBRD Base (A001–A017 from Lovable) ──
    [
        'reference' => 'ENG-2026-YBRD-A001',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_create',
        'current_stage' => 'CREATE',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
        ],
        'sample' => [
            'amount' => 120000,
            'invoice_number' => 'INV-YBRD-10000',
            'request_percentage' => 100,
            'import_type' => 'مواد غذائية',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'Cargill Inc.',
            'origin_country' => 'الولايات المتحدة',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A002',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_internal',
        'current_stage' => 'INTERNAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 340000,
            'invoice_number' => 'INV-YBRD-10011',
            'request_percentage' => 100,
            'import_type' => 'قطع غيار',
            'importer_name' => 'مجموعة الشيباني',
            'supplier_name' => 'Siemens AG',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A003',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_support',
        'current_stage' => 'SUPPORT',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 510000,
            'invoice_number' => 'INV-YBRD-10022',
            'request_percentage' => 100,
            'import_type' => 'أدوية ومستلزمات طبية',
            'importer_name' => 'شركة ثابت إخوان',
            'supplier_name' => 'Pfizer Ltd.',
            'origin_country' => 'الولايات المتحدة',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A004',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_support',
        'current_stage' => 'SUPPORT',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 89000,
            'invoice_number' => 'INV-YBRD-10033',
            'request_percentage' => 100,
            'import_type' => 'أدوية ومستلزمات طبية',
            'importer_name' => 'شركة الكميم للأدوية',
            'supplier_name' => 'Bayer AG',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A005',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_exec',
        'current_stage' => 'EXEC',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 720000,
            'invoice_number' => 'INV-YBRD-10044',
            'request_percentage' => 100,
            'import_type' => 'مشتقات نفطية',
            'importer_name' => 'مجموعة الأهدل',
            'supplier_name' => 'Saudi Aramco Trading',
            'origin_country' => 'السعودية',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A006',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_exec',
        'current_stage' => 'EXEC',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 145000,
            'invoice_number' => 'INV-YBRD-10055',
            'request_percentage' => 100,
            'import_type' => 'إلكترونيات',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'Siemens AG',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A007',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_fx',
        'current_stage' => 'FX',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 980000,
            'invoice_number' => 'INV-YBRD-10066',
            'request_percentage' => 100,
            'import_type' => 'مواد غذائية',
            'importer_name' => 'مجموعة الشيباني',
            'supplier_name' => 'Cargill Inc.',
            'origin_country' => 'الولايات المتحدة',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A008',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_fx',
        'current_stage' => 'FX',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 230000,
            'invoice_number' => 'INV-YBRD-10077',
            'request_percentage' => 100,
            'import_type' => 'مواد بناء',
            'importer_name' => 'شركة ثابت إخوان',
            'supplier_name' => 'Siemens AG',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A009',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_fx_confirm',
        'current_stage' => 'FX_CONFIRM',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 415000,
            'invoice_number' => 'INV-YBRD-10088',
            'request_percentage' => 100,
            'import_type' => 'أدوية ومستلزمات طبية',
            'importer_name' => 'شركة الكميم للأدوية',
            'supplier_name' => 'Pfizer Ltd.',
            'origin_country' => 'الولايات المتحدة',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A010',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_fx_confirm',
        'current_stage' => 'FX_CONFIRM',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 1250000,
            'invoice_number' => 'INV-YBRD-10099',
            'request_percentage' => 100,
            'import_type' => 'مشتقات نفطية',
            'importer_name' => 'مجموعة الأهدل',
            'supplier_name' => 'Saudi Aramco Trading',
            'origin_country' => 'السعودية',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A011',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_final',
        'current_stage' => 'FINAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FINAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 640000,
            'invoice_number' => 'INV-YBRD-10110',
            'request_percentage' => 100,
            'import_type' => 'مواد غذائية',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'Cargill Inc.',
            'origin_country' => 'الولايات المتحدة',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A012',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_final',
        'current_stage' => 'FINAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FINAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 1100000,
            'invoice_number' => 'INV-YBRD-10121',
            'request_percentage' => 100,
            'import_type' => 'مشتقات نفطية',
            'importer_name' => 'مجموعة الشيباني',
            'supplier_name' => 'Saudi Aramco Trading',
            'origin_country' => 'السعودية',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A013',
        'bank' => 'YBRD',
        'scenario_key' => 'lovable_sample_final',
        'current_stage' => 'FINAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FINAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 420000,
            'invoice_number' => 'INV-YBRD-10132',
            'request_percentage' => 100,
            'import_type' => 'إلكترونيات',
            'importer_name' => 'شركة ثابت إخوان',
            'supplier_name' => 'Bayer AG',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A014',
        'bank' => 'YBRD',
        'scenario_key' => 'completed',
        'current_stage' => 'CLOSED_COMPLETED',
        'runtime_status' => 'CLOSED',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FINAL', 'APPROVE'],
            ['FINAL', 'CLOSED_COMPLETED', 'FINAL_APPROVE'],
        ],
        'sample' => [
            'amount' => 540000,
            'invoice_number' => 'INV-YBRD-10143',
            'request_percentage' => 100,
            'import_type' => 'مواد غذائية',
            'importer_name' => 'مجموعة الأهدل',
            'supplier_name' => 'Cargill Inc.',
            'origin_country' => 'الولايات المتحدة',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A015',
        'bank' => 'YBRD',
        'scenario_key' => 'completed',
        'current_stage' => 'CLOSED_COMPLETED',
        'runtime_status' => 'CLOSED',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FINAL', 'APPROVE'],
            ['FINAL', 'CLOSED_COMPLETED', 'FINAL_APPROVE'],
        ],
        'sample' => [
            'amount' => 1280000,
            'invoice_number' => 'INV-YBRD-10154',
            'request_percentage' => 100,
            'import_type' => 'قطع غيار',
            'importer_name' => 'شركة الكميم للأدوية',
            'supplier_name' => 'Siemens AG',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A016',
        'bank' => 'YBRD',
        'scenario_key' => 'rejected',
        'current_stage' => 'CLOSED_REJECTED',
        'runtime_status' => 'REJECTED',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'CLOSED_REJECTED', 'REJECT_FINAL'],
        ],
        'sample' => [
            'amount' => 980000,
            'invoice_number' => 'INV-YBRD-10165',
            'request_percentage' => 100,
            'import_type' => 'مشتقات نفطية',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'Saudi Aramco Trading',
            'origin_country' => 'السعودية',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A017',
        'bank' => 'YBRD',
        'scenario_key' => 'rejected',
        'current_stage' => 'CLOSED_REJECTED',
        'runtime_status' => 'REJECTED',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'CLOSED_REJECTED', 'REJECT_FINAL'],
        ],
        'sample' => [
            'amount' => 350000,
            'invoice_number' => 'INV-YBRD-10176',
            'request_percentage' => 100,
            'import_type' => 'أجهزة كهربائية',
            'importer_name' => 'مجموعة الشيباني',
            'supplier_name' => 'LG Corporation',
            'origin_country' => 'كوريا الجنوبية',
        ],
    ],

    // ── YBRD Edge Scenarios (A018–A028) ──
    [
        'reference' => 'ENG-2026-YBRD-A018',
        'bank' => 'YBRD',
        'scenario_key' => 'returned_to_entry',
        'current_stage' => 'CREATE',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'CREATE', 'REJECT'],
        ],
        'sample' => [
            'amount' => 200000,
            'invoice_number' => 'INV-YBRD-A018-001',
            'request_percentage' => 100,
            'import_type' => 'مواد كيميائية',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'BASF SE',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A019',
        'bank' => 'YBRD',
        'scenario_key' => 'returned_to_fx',
        'current_stage' => 'FX',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FX', 'REJECT'],
        ],
        'sample' => [
            'amount' => 375000,
            'invoice_number' => 'INV-YBRD-A019-001',
            'request_percentage' => 100,
            'import_type' => 'نسيج وملابس',
            'importer_name' => 'مجموعة الأهدل',
            'supplier_name' => 'Inditex Group',
            'origin_country' => 'إسبانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A020',
        'bank' => 'YBRD',
        'scenario_key' => 'returned_to_fx_confirm',
        'current_stage' => 'FX_CONFIRM',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FINAL', 'APPROVE'],
            ['FINAL', 'FX_CONFIRM', 'REJECT'],
        ],
        'sample' => [
            'amount' => 550000,
            'invoice_number' => 'INV-YBRD-A020-001',
            'request_percentage' => 100,
            'import_type' => 'معدات صناعية',
            'importer_name' => 'شركة ثابت إخوان',
            'supplier_name' => 'ABB Ltd.',
            'origin_country' => 'سويسرا',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A021',
        'bank' => 'YBRD',
        'scenario_key' => 'claim_active',
        'current_stage' => 'SUPPORT',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 300000,
            'invoice_number' => 'INV-YBRD-A021-001',
            'request_percentage' => 100,
            'import_type' => 'معادن ثمينة',
            'importer_name' => 'شركة الكميم للأدوية',
            'supplier_name' => 'Johnson Matthey',
            'origin_country' => 'المملكة المتحدة',
        ],
        'claim_active' => true,
    ],
    [
        'reference' => 'ENG-2026-YBRD-A022',
        'bank' => 'YBRD',
        'scenario_key' => 'claim_expired',
        'current_stage' => 'SUPPORT',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 250000,
            'invoice_number' => 'INV-YBRD-A022-001',
            'request_percentage' => 100,
            'import_type' => 'أغذية مجمدة',
            'importer_name' => 'مجموعة الأهدل',
            'supplier_name' => 'Friona Foods',
            'origin_country' => 'الولايات المتحدة',
        ],
        'claim_expired' => true,
    ],
    [
        'reference' => 'ENG-2026-YBRD-A023',
        'bank' => 'YBRD',
        'scenario_key' => 'duplicate_invoice',
        'current_stage' => 'INTERNAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 180000,
            'invoice_number' => 'INV-DUP-SEED-001',
            'request_percentage' => 100,
            'import_type' => 'مواد بناء',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'HeidelbergCement',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A024',
        'bank' => 'YBRD',
        'scenario_key' => 'scan_pending',
        'current_stage' => 'INTERNAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 220000,
            'invoice_number' => 'INV-YBRD-A024-001',
            'request_percentage' => 100,
            'import_type' => 'معدات كهربائية',
            'importer_name' => 'مجموعة الشيباني',
            'supplier_name' => 'Schneider Electric',
            'origin_country' => 'فرنسا',
        ],
        'scan_status' => 'pending',
    ],
    [
        'reference' => 'ENG-2026-YBRD-A025',
        'bank' => 'YBRD',
        'scenario_key' => 'scan_failed',
        'current_stage' => 'INTERNAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 290000,
            'invoice_number' => 'INV-YBRD-A025-001',
            'request_percentage' => 100,
            'import_type' => 'قطع الآلات',
            'importer_name' => 'شركة ثابت إخوان',
            'supplier_name' => 'MTU Engines',
            'origin_country' => 'ألمانيا',
        ],
        'scan_status' => 'failed',
    ],
    [
        'reference' => 'ENG-2026-YBRD-A026',
        'bank' => 'YBRD',
        'scenario_key' => 'scan_infected',
        'current_stage' => 'INTERNAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 160000,
            'invoice_number' => 'INV-YBRD-A026-001',
            'request_percentage' => 100,
            'import_type' => 'أوراق وكرتون',
            'importer_name' => 'شركة الكميم للأدوية',
            'supplier_name' => 'International Paper',
            'origin_country' => 'الولايات المتحدة',
        ],
        'scan_status' => 'infected',
    ],
    [
        'reference' => 'ENG-2026-YBRD-A027',
        'bank' => 'YBRD',
        'scenario_key' => 'claim_released',
        'current_stage' => 'EXEC',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 425000,
            'invoice_number' => 'INV-YBRD-A027-001',
            'request_percentage' => 100,
            'import_type' => 'أنسجة تقنية',
            'importer_name' => 'مجموعة الأهدل',
            'supplier_name' => 'Textiles Intex',
            'origin_country' => 'إيطاليا',
        ],
    ],
    [
        'reference' => 'ENG-2026-YBRD-A028',
        'bank' => 'YBRD',
        'scenario_key' => 'document_replaced',
        'current_stage' => 'INTERNAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 315000,
            'invoice_number' => 'INV-YBRD-A028-001',
            'request_percentage' => 100,
            'import_type' => 'الآلات الصناعية',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'Mitsubishi Heavy',
            'origin_country' => 'اليابان',
        ],
        'document_replaced' => true,
    ],

    // ── CAC Base (A001–A017 from Lovable) ──
    [
        'reference' => 'ENG-2026-CAC-A001',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_create',
        'current_stage' => 'CREATE',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
        ],
        'sample' => [
            'amount' => 120000,
            'invoice_number' => 'INV-CAC-10000',
            'request_percentage' => 100,
            'import_type' => 'مواد غذائية',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'Cargill Inc.',
            'origin_country' => 'الولايات المتحدة',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A002',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_internal',
        'current_stage' => 'INTERNAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 340000,
            'invoice_number' => 'INV-CAC-10011',
            'request_percentage' => 100,
            'import_type' => 'قطع غيار',
            'importer_name' => 'مجموعة الشيباني',
            'supplier_name' => 'Siemens AG',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A003',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_support',
        'current_stage' => 'SUPPORT',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 510000,
            'invoice_number' => 'INV-CAC-10022',
            'request_percentage' => 100,
            'import_type' => 'أدوية ومستلزمات طبية',
            'importer_name' => 'شركة ثابت إخوان',
            'supplier_name' => 'Pfizer Ltd.',
            'origin_country' => 'الولايات المتحدة',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A004',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_support',
        'current_stage' => 'SUPPORT',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 89000,
            'invoice_number' => 'INV-CAC-10033',
            'request_percentage' => 100,
            'import_type' => 'أدوية ومستلزمات طبية',
            'importer_name' => 'شركة الكميم للأدوية',
            'supplier_name' => 'Bayer AG',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A005',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_exec',
        'current_stage' => 'EXEC',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 720000,
            'invoice_number' => 'INV-CAC-10044',
            'request_percentage' => 100,
            'import_type' => 'مشتقات نفطية',
            'importer_name' => 'مجموعة الأهدل',
            'supplier_name' => 'Saudi Aramco Trading',
            'origin_country' => 'السعودية',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A006',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_exec',
        'current_stage' => 'EXEC',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 145000,
            'invoice_number' => 'INV-CAC-10055',
            'request_percentage' => 100,
            'import_type' => 'إلكترونيات',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'Siemens AG',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A007',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_fx',
        'current_stage' => 'FX',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 980000,
            'invoice_number' => 'INV-CAC-10066',
            'request_percentage' => 100,
            'import_type' => 'مواد غذائية',
            'importer_name' => 'مجموعة الشيباني',
            'supplier_name' => 'Cargill Inc.',
            'origin_country' => 'الولايات المتحدة',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A008',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_fx',
        'current_stage' => 'FX',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 230000,
            'invoice_number' => 'INV-CAC-10077',
            'request_percentage' => 100,
            'import_type' => 'مواد بناء',
            'importer_name' => 'شركة ثابت إخوان',
            'supplier_name' => 'Siemens AG',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A009',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_fx_confirm',
        'current_stage' => 'FX_CONFIRM',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 415000,
            'invoice_number' => 'INV-CAC-10088',
            'request_percentage' => 100,
            'import_type' => 'أدوية ومستلزمات طبية',
            'importer_name' => 'شركة الكميم للأدوية',
            'supplier_name' => 'Pfizer Ltd.',
            'origin_country' => 'الولايات المتحدة',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A010',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_fx_confirm',
        'current_stage' => 'FX_CONFIRM',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 1250000,
            'invoice_number' => 'INV-CAC-10099',
            'request_percentage' => 100,
            'import_type' => 'مشتقات نفطية',
            'importer_name' => 'مجموعة الأهدل',
            'supplier_name' => 'Saudi Aramco Trading',
            'origin_country' => 'السعودية',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A011',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_final',
        'current_stage' => 'FINAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FINAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 640000,
            'invoice_number' => 'INV-CAC-10110',
            'request_percentage' => 100,
            'import_type' => 'مواد غذائية',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'Cargill Inc.',
            'origin_country' => 'الولايات المتحدة',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A012',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_final',
        'current_stage' => 'FINAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FINAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 1100000,
            'invoice_number' => 'INV-CAC-10121',
            'request_percentage' => 100,
            'import_type' => 'مشتقات نفطية',
            'importer_name' => 'مجموعة الشيباني',
            'supplier_name' => 'Saudi Aramco Trading',
            'origin_country' => 'السعودية',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A013',
        'bank' => 'CAC',
        'scenario_key' => 'lovable_sample_final',
        'current_stage' => 'FINAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FINAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 420000,
            'invoice_number' => 'INV-CAC-10132',
            'request_percentage' => 100,
            'import_type' => 'إلكترونيات',
            'importer_name' => 'شركة ثابت إخوان',
            'supplier_name' => 'Bayer AG',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A014',
        'bank' => 'CAC',
        'scenario_key' => 'completed',
        'current_stage' => 'CLOSED_COMPLETED',
        'runtime_status' => 'CLOSED',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FINAL', 'APPROVE'],
            ['FINAL', 'CLOSED_COMPLETED', 'FINAL_APPROVE'],
        ],
        'sample' => [
            'amount' => 540000,
            'invoice_number' => 'INV-CAC-10143',
            'request_percentage' => 100,
            'import_type' => 'مواد غذائية',
            'importer_name' => 'مجموعة الأهدل',
            'supplier_name' => 'Cargill Inc.',
            'origin_country' => 'الولايات المتحدة',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A015',
        'bank' => 'CAC',
        'scenario_key' => 'completed',
        'current_stage' => 'CLOSED_COMPLETED',
        'runtime_status' => 'CLOSED',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FINAL', 'APPROVE'],
            ['FINAL', 'CLOSED_COMPLETED', 'FINAL_APPROVE'],
        ],
        'sample' => [
            'amount' => 1280000,
            'invoice_number' => 'INV-CAC-10154',
            'request_percentage' => 100,
            'import_type' => 'قطع غيار',
            'importer_name' => 'شركة الكميم للأدوية',
            'supplier_name' => 'Siemens AG',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A016',
        'bank' => 'CAC',
        'scenario_key' => 'rejected',
        'current_stage' => 'CLOSED_REJECTED',
        'runtime_status' => 'REJECTED',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'CLOSED_REJECTED', 'REJECT_FINAL'],
        ],
        'sample' => [
            'amount' => 980000,
            'invoice_number' => 'INV-CAC-10165',
            'request_percentage' => 100,
            'import_type' => 'مشتقات نفطية',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'Saudi Aramco Trading',
            'origin_country' => 'السعودية',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A017',
        'bank' => 'CAC',
        'scenario_key' => 'rejected',
        'current_stage' => 'CLOSED_REJECTED',
        'runtime_status' => 'REJECTED',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'CLOSED_REJECTED', 'REJECT_FINAL'],
        ],
        'sample' => [
            'amount' => 350000,
            'invoice_number' => 'INV-CAC-10176',
            'request_percentage' => 100,
            'import_type' => 'أجهزة كهربائية',
            'importer_name' => 'مجموعة الشيباني',
            'supplier_name' => 'LG Corporation',
            'origin_country' => 'كوريا الجنوبية',
        ],
    ],

    // ── CAC Edge Scenarios (A018–A028) ──
    [
        'reference' => 'ENG-2026-CAC-A018',
        'bank' => 'CAC',
        'scenario_key' => 'returned_to_entry',
        'current_stage' => 'CREATE',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'CREATE', 'REJECT'],
        ],
        'sample' => [
            'amount' => 200000,
            'invoice_number' => 'INV-CAC-A018-001',
            'request_percentage' => 100,
            'import_type' => 'مواد كيميائية',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'BASF SE',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A019',
        'bank' => 'CAC',
        'scenario_key' => 'returned_to_fx',
        'current_stage' => 'FX',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FX', 'REJECT'],
        ],
        'sample' => [
            'amount' => 375000,
            'invoice_number' => 'INV-CAC-A019-001',
            'request_percentage' => 100,
            'import_type' => 'نسيج وملابس',
            'importer_name' => 'مجموعة الأهدل',
            'supplier_name' => 'Inditex Group',
            'origin_country' => 'إسبانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A020',
        'bank' => 'CAC',
        'scenario_key' => 'returned_to_fx_confirm',
        'current_stage' => 'FX_CONFIRM',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
            ['EXEC', 'FX', 'APPROVE'],
            ['FX', 'FX_CONFIRM', 'APPROVE'],
            ['FX_CONFIRM', 'FINAL', 'APPROVE'],
            ['FINAL', 'FX_CONFIRM', 'REJECT'],
        ],
        'sample' => [
            'amount' => 550000,
            'invoice_number' => 'INV-CAC-A020-001',
            'request_percentage' => 100,
            'import_type' => 'معدات صناعية',
            'importer_name' => 'شركة ثابت إخوان',
            'supplier_name' => 'ABB Ltd.',
            'origin_country' => 'سويسرا',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A021',
        'bank' => 'CAC',
        'scenario_key' => 'claim_active',
        'current_stage' => 'SUPPORT',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 300000,
            'invoice_number' => 'INV-CAC-A021-001',
            'request_percentage' => 100,
            'import_type' => 'معادن ثمينة',
            'importer_name' => 'شركة الكميم للأدوية',
            'supplier_name' => 'Johnson Matthey',
            'origin_country' => 'المملكة المتحدة',
        ],
        'claim_active' => true,
    ],
    [
        'reference' => 'ENG-2026-CAC-A022',
        'bank' => 'CAC',
        'scenario_key' => 'claim_expired',
        'current_stage' => 'SUPPORT',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 250000,
            'invoice_number' => 'INV-CAC-A022-001',
            'request_percentage' => 100,
            'import_type' => 'أغذية مجمدة',
            'importer_name' => 'مجموعة الأهدل',
            'supplier_name' => 'Friona Foods',
            'origin_country' => 'الولايات المتحدة',
        ],
        'claim_expired' => true,
    ],
    [
        'reference' => 'ENG-2026-CAC-A023',
        'bank' => 'CAC',
        'scenario_key' => 'duplicate_invoice',
        'current_stage' => 'INTERNAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 180000,
            'invoice_number' => 'INV-DUP-SEED-001',
            'request_percentage' => 100,
            'import_type' => 'مواد بناء',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'HeidelbergCement',
            'origin_country' => 'ألمانيا',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A024',
        'bank' => 'CAC',
        'scenario_key' => 'scan_pending',
        'current_stage' => 'INTERNAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 220000,
            'invoice_number' => 'INV-CAC-A024-001',
            'request_percentage' => 100,
            'import_type' => 'معدات كهربائية',
            'importer_name' => 'مجموعة الشيباني',
            'supplier_name' => 'Schneider Electric',
            'origin_country' => 'فرنسا',
        ],
        'scan_status' => 'pending',
    ],
    [
        'reference' => 'ENG-2026-CAC-A025',
        'bank' => 'CAC',
        'scenario_key' => 'scan_failed',
        'current_stage' => 'INTERNAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 290000,
            'invoice_number' => 'INV-CAC-A025-001',
            'request_percentage' => 100,
            'import_type' => 'قطع الآلات',
            'importer_name' => 'شركة ثابت إخوان',
            'supplier_name' => 'MTU Engines',
            'origin_country' => 'ألمانيا',
        ],
        'scan_status' => 'failed',
    ],
    [
        'reference' => 'ENG-2026-CAC-A026',
        'bank' => 'CAC',
        'scenario_key' => 'scan_infected',
        'current_stage' => 'INTERNAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 160000,
            'invoice_number' => 'INV-CAC-A026-001',
            'request_percentage' => 100,
            'import_type' => 'أوراق وكرتون',
            'importer_name' => 'شركة الكميم للأدوية',
            'supplier_name' => 'International Paper',
            'origin_country' => 'الولايات المتحدة',
        ],
        'scan_status' => 'infected',
    ],
    [
        'reference' => 'ENG-2026-CAC-A027',
        'bank' => 'CAC',
        'scenario_key' => 'claim_released',
        'current_stage' => 'EXEC',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
            ['INTERNAL', 'SUPPORT', 'APPROVE'],
            ['SUPPORT', 'EXEC', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 425000,
            'invoice_number' => 'INV-CAC-A027-001',
            'request_percentage' => 100,
            'import_type' => 'أنسجة تقنية',
            'importer_name' => 'مجموعة الأهدل',
            'supplier_name' => 'Textiles Intex',
            'origin_country' => 'إيطاليا',
        ],
    ],
    [
        'reference' => 'ENG-2026-CAC-A028',
        'bank' => 'CAC',
        'scenario_key' => 'document_replaced',
        'current_stage' => 'INTERNAL',
        'runtime_status' => 'ACTIVE',
        'path' => [
            ['CREATE', null, 'CREATE'],
            ['CREATE', 'INTERNAL', 'APPROVE'],
        ],
        'sample' => [
            'amount' => 315000,
            'invoice_number' => 'INV-CAC-A028-001',
            'request_percentage' => 100,
            'import_type' => 'الآلات الصناعية',
            'importer_name' => 'شركة هائل سعيد أنعم',
            'supplier_name' => 'Mitsubishi Heavy',
            'origin_country' => 'اليابان',
        ],
        'document_replaced' => true,
    ],
];
