<?php

namespace App\Enums;

enum FieldSemanticTag: string
{
    case INVOICE_NUMBER = 'INVOICE_NUMBER';
    case REQUESTED_PERCENTAGE = 'REQUESTED_PERCENTAGE';
    case MERCHANT_TAX_NUMBER = 'MERCHANT_TAX_NUMBER';
    case SUPPLIER_NAME = 'SUPPLIER_NAME';
    case GOODS_DESCRIPTION = 'GOODS_DESCRIPTION';
    case PORT_OF_ENTRY = 'PORT_OF_ENTRY';
    case AMOUNT = 'AMOUNT';
    case CURRENCY = 'CURRENCY';
    case MERCHANT_ID = 'MERCHANT_ID';
    case MERCHANT_COMPANY_ID = 'MERCHANT_COMPANY_ID';
    case MERCHANT_TAX_CARD_EXPIRY = 'MERCHANT_TAX_CARD_EXPIRY';
    case MERCHANT_COMMERCIAL_REGISTRATION_NUMBER = 'MERCHANT_COMMERCIAL_REGISTRATION_NUMBER';
    case MERCHANT_COMMERCIAL_REGISTRATION_EXPIRY = 'MERCHANT_COMMERCIAL_REGISTRATION_EXPIRY';
    case MERCHANT_OWNERS = 'MERCHANT_OWNERS';
}
