<?php

namespace App\Enums;

enum WorkflowAction: string
{
    case SUBMIT = 'SUBMIT';
    case BANK_APPROVE = 'BANK_APPROVE';
    case BANK_REJECT = 'BANK_REJECT';
    case RETURN_TO_DATA_ENTRY = 'RETURN_TO_DATA_ENTRY';
    case SUPPORT_APPROVE = 'SUPPORT_APPROVE';
    case SUPPORT_REJECT = 'SUPPORT_REJECT';
    case UPLOAD_SWIFT = 'UPLOAD_SWIFT';
    case START_EXECUTIVE_VOTING = 'START_EXECUTIVE_VOTING';
    case EXECUTIVE_APPROVE = 'EXECUTIVE_APPROVE';
    case EXECUTIVE_REJECT = 'EXECUTIVE_REJECT';
    case ISSUE_CUSTOMS = 'ISSUE_CUSTOMS';
    case COMPLETE = 'COMPLETE';
}
